version: '3'
services:
  app-qa-polling:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/flagship-io/flagship-php-sdk-dev:qa
    container_name: app-qa-polling
    restart: unless-stopped
    environment:
      SERVICE_NAME: app-qa-polling
      SERVICE_TAGS: qa
    command: vendor/bin/flagship --config=storage/app/flagship/flagship.json
    volumes:
      - flagship-volume:/var/www/html/storage/app/flagship
    working_dir: /var/www/html

  app-qa-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/flagship-io/flagship-php-sdk-dev:qa
    container_name: app-qa-web
    restart: unless-stopped
    environment:
      SERVICE_NAME: app-qa-web
      SERVICE_TAGS: qa
    ports:
      - 0.0.0.0:80:80
    volumes:
      - flagship-volume:/var/www/html/storage/app/flagship
    working_dir: /var/www/html
volumes:
  flagship-volume:
