<?php

namespace Flagship\Enum;

enum TroubleshootingLabel: string
{
    case VISITOR_FETCH_CAMPAIGNS = "VISITOR_FETCH_CAMPAIGNS";
    case VISITOR_FETCH_CAMPAIGNS_ERROR = "VISITOR_FETCH_CAMPAIGNS_ERROR";
    case SEND_BATCH_HIT_ROUTE_RESPONSE_ERROR = "SEND_BATCH_HIT_ROUTE_RESPONSE_ERROR";
    case SEND_ACTIVATE_HIT_ROUTE_ERROR = "SEND_ACTIVATE_HIT_ROUTE_ERROR";
    case VISITOR_SEND_ACTIVATE = "VISITOR_SEND_ACTIVATE";
    case VISITOR_SEND_HIT = "VISITOR_SEND_HIT";
    case VISITOR_AUTHENTICATE = "VISITOR_AUTHENTICATE";
    case VISITOR_UNAUTHENTICATE = "VISITOR_UNAUTHENTICATE";
    case VISITOR_EXPOSED_FLAG_NOT_FOUND = "VISITOR_EXPOSED_FLAG_NOT_FOUND";
    case VISITOR_EXPOSED_TYPE_WARNING = "VISITOR_EXPOSED_TYPE_WARNING";
    case GET_FLAG_VALUE_FLAG_NOT_FOUND = "GET_FLAG_VALUE_FLAG_NOT_FOUND";
    case GET_FLAG_VALUE_TYPE_WARNING = "GET_FLAG_VALUE_TYPE_WARNING";
    case GET_FLAG_METADATA_TYPE_WARNING = "GET_FLAG_METADATA_TYPE_WARNING";
    case GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR = "GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR";
    case SDK_BUCKETING_FILE_ERROR = "SDK_BUCKETING_FILE_ERROR";
    case SDK_BUCKETING_FILE = "SDK_BUCKETING_FILE";
    case SDK_CONFIG = "SDK_CONFIG";
    case SEND_HIT_ROUTE_ERROR = "SEND_HIT_ROUTE_ERROR";
    case FLAG_VALUE_NOT_CALLED = "FLAG_VALUE_NOT_CALLED";
}
