<?php

namespace Flagship\Enum;

class TroubleshootingLabel
{
    const VISITOR_FETCH_CAMPAIGNS = "VISITOR_FETCH_CAMPAIGNS";
    const VISITOR_FETCH_CAMPAIGNS_ERROR = "VISITOR_FETCH_CAMPAIGNS_ERROR";
    const SEND_BATCH_HIT_ROUTE_RESPONSE_ERROR = "SEND_BATCH_HIT_ROUTE_RESPONSE_ERROR";

    const SEND_ACTIVATE_HIT_ROUTE_ERROR= "SEND_ACTIVATE_HIT_ROUTE_ERROR";
    const VISITOR_SEND_ACTIVATE = "VISITOR_SEND_ACTIVATE";
    const VISITOR_SEND_HIT= "VISITOR_SEND_HIT";
    const VISITOR_AUTHENTICATE = "VISITOR_AUTHENTICATE";
    const VISITOR_UNAUTHENTICATE = "VISITOR_UNAUTHENTICATE";
    const VISITOR_EXPOSED_FLAG_NOT_FOUND = "VISITOR_EXPOSED_FLAG_NOT_FOUND";
    const VISITOR_EXPOSED_TYPE_WARNING = "VISITOR_EXPOSED_TYPE_WARNING";
    const GET_FLAG_VALUE_FLAG_NOT_FOUND= "GET_FLAG_VALUE_FLAG_NOT_FOUND";
    const GET_FLAG_VALUE_TYPE_WARNING = "GET_FLAG_VALUE_TYPE_WARNING";
    const GET_FLAG_METADATA_TYPE_WARNING= "GET_FLAG_METADATA_TYPE_WARNING";
    const GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR = "GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR";
    const SDK_BUCKETING_FILE_ERROR= "SDK_BUCKETING_FILE_ERROR";
    const SDK_BUCKETING_FILE = "SDK_BUCKETING_FILE";
    const SDK_CONFIG = "SDK_CONFIG";
    const SEND_HIT_ROUTE_ERROR = 'SEND_HIT_ROUTE_ERROR';
}
