<?php

namespace Flagship\Enum;

class TroubleshootingLabel
{
    const VISITOR_FETCH_CAMPAIGNS = "VISITOR-FETCH-CAMPAIGNS";
    const VISITOR_FETCH_CAMPAIGNS_ERROR = "VISITOR-FETCH-CAMPAIGNS-ERROR";
    const VISITOR_SEND_ACTIVATE = "VISITOR-SEND-ACTIVATE";
    const VISITOR_SEND_HIT= "VISITOR-SEND-HIT";
    const VISITOR_AUTHENTICATE = "VISITOR-AUTHENTICATE";
    const VISITOR_UNAUTHENTICATE = "VISITOR-UNAUTHENTICATE";
    const VISITOR_EXPOSED_FLAG_NOT_FOUND = "VISITOR-EXPOSED-FLAG-NOT-FOUND";
    const VISITOR_EXPOSED_TYPE_WARNING = "VISITOR-EXPOSED-TYPE-WARNING";
    const GET_FLAG_VALUE_FLAG_NOT_FOUND= "GET-FLAG-VALUE-FLAG-NOT-FOUND";
    const GET_FLAG_VALUE_TYPE_WARNING = "GET-FLAG-VALUE-TYPE-WARNING";
    const GET_FLAG_METADATA_TYPE_WARNING= "GET-FLAG-METADATA-TYPE-WARNING";
    const GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR = "GET-CAMPAIGNS-ROUTE-RESPONSE-ERROR";
    const SDK_BUCKETING_FILE_ERROR= "SDK-BUCKETING-FILE-ERROR";
    const SDK_BUCKETING_FILE = "SDK-BUCKETING-FILE";
}
