FROM defconjuan/docker-php-5.4 as php-5-4
COPY . /home/app
WORKDIR /home/app

RUN apt-get update

RUN apt-get upgrade -y --force-yes

Run pecl channel-update pecl.php.net
RUN pecl install xdebug-2.2.3
Run docker-php-ext-enable xdebug

RUN apt-get install -y --force-yes libzip-dev zlib1g-dev

RUN docker-php-ext-install zip

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer remove psr/log --no-update
RUN composer remove phpunit/phpunit --no-update

#RUN composer require psr/log:^1 -W
#RUN composer require phpunit/phpunit -W

#RUN composer install