FROM php:8-alpine
COPY . /home/app
WORKDIR /home/app

RUN apk add --update linux-headers

RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS}
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN apk del pcre-dev ${PHPIZE_DEPS}

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer remove phpunit/phpunit --dev

RUN composer install

RUN composer require phpunit/phpunit --dev

