version: '3'
services:
  app-polling:
    image: flagshipio/sync-agent
    container_name: app-polling
    environment:
      SERVICE_NAME: app-polling
      SERVICE_TAGS: dev
      FS_ENV_ID: bk87t3jggr10c6l6sdog
    ports:
      - "3000:8080"
    networks:
      - app_network

  app-8:
    build:
      context: ../.
      dockerfile: ./dockers/Dockerfile
    image: flagship-io/flagship-php-sdk:php-8
    container_name: app-8
    tty: true
    environment:
      SERVICE_NAME: app-8
      SERVICE_TAGS: dev
      XDEBUG_MODE: coverage
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_POLLING_HOST: app-polling
      APP_POLLING_PORT: 8080
    volumes:
      - '..:/home/app'
    ports:
      - "8001:8000"
    working_dir: /home/app
    networks:
      - app_network

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
#    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
        - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge