FROM defconjuan/docker-php-5.4 as php-5-4
COPY . /home/app
WORKDIR /home/app

RUN echo "deb http://archive.debian.org/debian/ jessie main" > /etc/apt/sources.list
RUN echo "deb-src http://archive.debian.org/debian/ jessie main" >> /etc/apt/sources.list
RUN echo "Acquire::Check-Valid-Until false;" > /etc/apt/apt.conf.d/99no-check-valid-until

RUN apt-get update

RUN apt-get install -y php-pear php5-dev --force-yes

#RUN apt-get upgrade -y --force-yes
RUN mkdir -p /tmp/pear/cache


RUN apt-get install -y --force-yes ca-certificates \
    && update-ca-certificates \
    && wget --no-check-certificate https://xdebug.org/files/xdebug-2.4.1.tgz \
    && tar -xvzf xdebug-2.4.1.tgz \
    && cd xdebug-2.4.1 \
    && phpize \
    && ./configure \
    && make \
    && cp modules/xdebug.so /usr/lib/php5/20131226 \
    && echo 'zend_extension = /usr/lib/php5/20131226/xdebug.so' >> /etc/php5/cli/php.ini
    
Run pecl channel-update pecl.php.net
RUN pecl clear-cache
RUN pecl install xdebug-2.4.1

RUN apt-get install -y --force-yes libzip-dev zlib1g-dev

RUN pecl install zip \
    && echo 'extension=zip.so' >> /etc/php5/cli/php.ini

RUN apt-get install -y --force-yes php5-curl \
    && echo 'extension=curl.so' >> /etc/php5/cli/php.ini

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer remove psr/log --no-update
RUN composer remove phpunit/phpunit --no-update

RUN composer require phpunit/phpunit --dev 
RUN composer require psr/log:^1

RUN composer install