version: '3'
services:

  #PHP Service
  app-5.4:
    build:
      context: ../.
      dockerfile: ./dockers/Dockerfile-5.4
    image: flagship-io/flagship-php-sdk:php-5.4
    container_name: app-5.4
    tty: true
    environment:
      SERVICE_NAME: app-5.4
      SERVICE_TAGS: dev
    volumes:
      - '..:/home/app'
    ports:
      - 8000:8000
    working_dir: /home/app