FROM php:7.4-alpine
COPY . /home/app
WORKDIR /home/app


RUN apk add git
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \ 
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}


RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer install

CMD vendor/bin/flagship --envId=${FLAGSHIP_ENV_ID} --pollingInterval=${FLAGSHIP_POLLING_INTERVAL} --bucketingPath=${FLAGSHIP_BUCKETING_DIRECTORY}