version: '3'
services:

  #PHP Service
  app-polling:
    build:
      context: .
      dockerfile: ./Dockerfile-polling
    image: flagship-io-polling/flagship-php-sdk:php-7.4
    container_name: app-polling
    tty: true
    environment:
      SERVICE_NAME: app-polling
      SERVICE_TAGS: dev
      XDEBUG_MODE: coverage
      FLAGSHIP-DOCKER: 1
      FLAGSHIP_ENV_ID: envId
      FLAGSHIP_POLLING_INTERVAL: 5000
    volumes:
      - bucketing-file:/home/app/flagship
      - ./gitAuth:/root/.composer/
    working_dir: /home/app

  app-demo:
    build:
      context: .
      dockerfile: ./Dockerfile-demo
    image: flagship-io-demo/flagship-php-sdk:php-7.4
    container_name: app-demo
    tty: true
    environment:
      SERVICE_NAME: app-demo
      SERVICE_TAGS: dev
      XDEBUG_MODE: coverage
      FLAGSHIP-DOCKER: 1
      FLAGSHIP_ENV_ID: envId
      FLAGSHIP_API_KEY: apiKey
      FLAGSHIP_POLLING_INTERVAL: 5000
    volumes:
      - bucketing-file:/home/app/flagship
      - ./gitAuth:/root/.composer/
    working_dir: /home/app
volumes:
  bucketing-file: