version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flagship-app-example
        env_file:
            - .env
        environment:
            - FS_SYNC_AGENT_HOST=fs_sync_agent
            - FS_SYNC_AGENT_PORT=8080
        container_name: flagship-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - flagship

    fs_sync_agent:
        image: flagshipio/sync-agent
        container_name: fs_sync_agent
        ports:
            - "3000:8080"
        env_file:
            - .env
        networks:
            - flagship
    nginx:
        image: nginx:alpine
        container_name: flagship-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - flagship

networks:
    flagship:
        driver: bridge
volumes:
    shared-volume:
