name: Build and deploy CI for QA

on:
  push:
    branches: [main, feature/sdk_v2]

jobs:
  testqa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example

    strategy:
      matrix:
        php-versions: [ '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-

      - name: Setup nightly PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, curl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test

  deployqa:

    needs: testqa
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_QA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:qa
          context: .
          file: ./Dockerfile
