name: Build and deploy CI for QA

on:
  push:
    branches: [feature/sdk_v2]
jobs:
  deployqa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_QA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:qa
          context: ./example/.
          file: ./example/Dockerfile
