name: CI PHP 8

on:
  push:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FS_API_KEY: "${{ secrets.FS_CI_CAMPAIGNS_API_KEY }}"
      FS_ENV_ID:  "${{ secrets.FS_CI_CAMPAIGNS_ENV_ID }}"

    strategy:
      matrix:
        php-versions: ['8']
        phpunit-versions: ['9']

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup nightly PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug        
        tools: phpunit:${{ matrix.phpunit-versions }}
        
    - name: Remove current phpunit version
      run: composer remove phpunit/phpunit --dev

    - name: install new phpunit version
      run: composer require phpunit/phpunit --dev

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test -- -c phpunit.8.xml

    - name: Run functional test
      run: php tests/TestFunctional.php
    
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./clover.xml
        flags: unittests
        name: codecov-flagship-php-coverage
        fail_ci_if_error: true


