name: Unit test & coverage

on:
  push:
    branches: [ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, curl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Install packages
        run: composer validate --strict

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v1
