version: '3'
services:
  app-qa-polling:
    image: flagshipio/sync-agent:1.0.0
    container_name: app-qa-polling
    restart: unless-stopped
    environment:
      SERVICE_NAME: app-qa-polling
      SERVICE_TAGS: qa
    command: ./app --config=storage/app/flagship/flagship.json
    volumes:
      - flagship-volume:/storage/app/flagship


  app-qa-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/flagship-io/flagship-php-sdk-dev:qa
    container_name: app-qa-web
    restart: unless-stopped
    environment:
      SERVICE_NAME: app-qa-web
      SERVICE_TAGS: qa
    ports:
      - 0.0.0.0:80:80
    volumes:
      - flagship-volume:/var/www/html/storage/app/flagship
      - app-log:/var/www/html/storage/logs
    working_dir: /var/www/html
volumes:
  flagship-volume:
  app-log:
